### ISSUE TITLE
Import WireGuard Via New Patcher, Not Directly in Tree

### ISSUE THREAD

**Issue by zx2c4** [nine7nine/Marlin_exns-eas#1]
Some recent WireGuard changes I thought I should tell you about here.

You've been building WireGuard as part of this kernel by actually committing the WireGuard source code. *Please stop doing this*, and instead move over to the new method, which was created in response to a few recent requests and concerns. It's also an *important* thing to do, because it ensures that things actually stay up to date. [The below instructions follow from "Standalone Kernel Built-in Module" in the documentation.](https://git.zx2c4.com/android_kernel_wireguard/about/)

First remove what you did before:

```
$ rm -rf path/to/kernel/net/wireguard # or just revert your previous commit
```

Now run the persistent patcher script and commit its results:

```
$ cd /tmp && git clone https://git.zx2c4.com/android_kernel_wireguard/
$ cd android_kernel_wireguard/standalone-kernel
$ ./patch-kernel.sh path/to/kernel
$ cd /tmp && rm -rf android_kernel_wireguard
$ cd path/to/kernel && git add . && git commit -m "net/wireguard: add to tree via updater mechanism"
```

That should be all that's required. This method is quite new, so it's possible there will be some friction, but let me know how it goes, and I'll address bugs quickly if there are any.

**Comment by nine7nine** [comment]
Thanks and will do - I was waiting for something like this to show up... What I had done in my previous tree ~ was watch your commits, (git-)format patch, adjust the path and apply them with the original commit intact... But this would be preferred....

thanks for the head's up. doing now

**Comment by zx2c4** [comment]
Cool. Let me know how it goes. It _might_ totally explode, but I hope it doesn't.

**Comment by nine7nine** [comment]
This all sounds good to me. 

committed: https://github.com/nine7nine/Marlin_exns-eas/commit
/1578ce64765ca708af89fbdc86b668a590fb8e3c

I'll just leave this issue open, for if/when things explode. I guess I won't know that until the next snapshot shows up.

**Comment by zx2c4** [comment]
Great! So it built on your box then? That's good news.

**Comment by nine7nine** [comment]
Ya man. I always compile before committing or pushing anything to my remote branch / github -)

I should've mentioned that, but I assumed that things blowing up would be later on, maybe...
